name: Update Packagist

on:
  release:
    types: [published]

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Packagist
        run: |
          curl -X POST "https://packagist.org/api/update-package?username=Vesper&apiToken=${{ secrets.PACKAGIST_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{"repository":{"url":"https://packagist.org/packages/vesper/unit-conversion"}}'
